#  Hugo versions 0.107.0 under https://gitlab.com/pages/hugo/container_registry.

image: registry.gitlab.com/pages/hugo/hugo_extended:0.107.0

# Git submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

default:
  before_script:
    - apk add --update --no-cache git go
    - git submodule update --init --recursive
    - hugo mod init gitlab.com/UniversalAmateur/universalamateur.gitlab.io
    - hugo mod get -u github.com/theNewDynamic/gohugo-theme-ananke

test:
  script:
    - hugo
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
