baseURL = 'https://Universalamateur.gitlab.io/' #Set Baseurl of own Site
languageCode = 'en-us'
title = 'Universalamateur'
theme = 'ananke' #Chosen Theme for hugo Page

contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public" #Set to public for GitLab Pages
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # Can be set higher or lower for performance
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The personal Blog of Universalamateur"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10

# The social activations for this blog enabled through https://github.com/theNewDynamic/gohugo-theme-ananke#social-follow--share
[[params.ananke_socials]]
  name = "gitlab"
  url = "https://gitlab.com/fsieverding"
[[params.ananke_socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/falko-sieverding-Universalamateur"
[[params.ananke_socials]]
  name= "mastodon"
  url= "https://fosstodon.org/@Universalamateur"
  rel= "me noopener"
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/Universalamateur"
[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/falkosieverding"

# Removing the default taxonomy category
[taxonomies]
  tag = 'tags'
